bool monitorWipeButton(uint32_t interval);
boolean isMaster( byte test[] );
void successDelete();
void failedWrite();
void successWrite();
boolean findID( byte find[] );
uint8_t findIDSLOT( byte find[] );
boolean checkTwo ( byte a[], byte b[] ) ;
void deleteID( byte a[] );
void writeID( byte a[] );
void readID( uint8_t number ) ;
void normalModeOn ();
void cycleLeds();
void ShowReaderDetails();
uint8_t getID();
void denied();
void granted ( uint16_t setDelay);
void dump_byte_array(byte *buffer, byte bufferSize);
void formatValueBlock(byte blockAddr);
